Script started on Fri 06 Nov 2015 11:52:15 PM PST
]0;emull005@hammer:~/CS100/rshell/tests[?1034h[emull005@hammer tests]$ cd ..
]0;emull005@hammer:~/CS100/rshell[emull005@hammer rshell]$ make
make rshell;
make[1]: Entering directory `/home/csmajs/emull005/CS100/rshell'
mkdir bin; g++ src/shell.c -Wall -Werror -ansi -pedantic -o bin/rshell 
mkdir: cannot create directory `bin': File exists
make[1]: Leaving directory `/home/csmajs/emull005/CS100/rshell'
]0;emull005@hammer:~/CS100/rshell[emull005@hammer rshell]$ bin/rseh[Kh[K[Khell
$: ls -a || pwd
.  ..  bin  .git  heya.c  heyo.c  LICENSE.md  Makefile	README.md  src	tests
$: ls || pwd || ps
bin  heya.c  heyo.c  LICENSE.md  Makefile  README.md  src  tests
  PID TTY          TIME CMD
47688 pts/8    00:00:00 bash
47729 pts/8    00:00:00 rshell
47769 pts/8    00:00:00 ps
$: asdf || pwd
execution failed: No such file or directory
/home/csmajs/emull005/CS100/rshell
$: asdf || pwd && ls;git branch
execution failed: No such file or directory
/home/csmajs/emull005/CS100/rshell
bin  heya.c  heyo.c  LICENSE.md  Makefile  README.md  src  tests
* exec
  master
$: abc; ls ;; pwd ; ; && ||
execution failed: No such file or directory
bin  heya.c  heyo.c  LICENSE.md  Makefile  README.md  src  tests
/home/csmajs/emull005/CS100/rshell
$: lsls || ls -a
execution failed: No such file or directory
.  ..  bin  .git  heya.c  heyo.c  LICENSE.md  Makefile	README.md  src	tests
$: pwd || ls || pwd || ls || pwd
/home/csmajs/emull005/CS100/rshell
/home/csmajs/emull005/CS100/rshell
/home/csmajs/emull005/CS100/rshell
$: pwd && ls && pwd && ls && pwd
/home/csmajs/emull005/CS100/rshell
bin  heya.c  heyo.c  LICENSE.md  Makefile  README.md  src  tests
/home/csmajs/emull005/CS100/rshell
bin  heya.c  heyo.c  LICENSE.md  Makefile  README.md  src  tests
/home/csmajs/emull005/CS100/rshell
$: pwd && ls || pwd && ls ; ps
/home/csmajs/emull005/CS100/rshell
bin  heya.c  heyo.c  LICENSE.md  Makefile  README.md  src  tests
bin  heya.c  heyo.c  LICENSE.md  Makefile  README.md  src  tests
  PID TTY          TIME CMD
47688 pts/8    00:00:00 bash
47729 pts/8    00:00:00 rshell
48092 pts/8    00:00:00 ps
$: exit
]0;emull005@hammer:~/CS100/rshell[emull005@hammer rshell]$ exit
exit

Script done on Fri 06 Nov 2015 11:56:10 PM PST
